[364] Added ability to set image tag for loaders
usdigitalresponse/univaf pull request #485
Opened 2021-12-01 03:31 UTC by jaronoff97

This PR changes the loader TF module to allow us to set the version for the image. By doing this, we will be able to make the image repositories immutable to prevent any image tags from getting overwritten. That work will be covered in a follow up PR so as to isolate the changes being made.

2021-12-01 03:47 UTC, jaronoff97 commented
The TF diff has to change the task definitions for all of the loaders, so we see thirteen changes in all.

2021-12-17 19:14 UTC, Mr0grog commented
Rebased so this merges cleanly.

2021-12-17 19:17 UTC, Mr0grog requested changes
Sorry I missed this was waiting on me! Looks good, except for the deprecated syntax. Fix that and let’s get this in!

2021-12-17 19:17 UTC, Mr0grog commented on terraform/modules/loader/main.tf
> +  image   = "${var.loader_image}"
Let’s fix the deprecation warning this triggers:

```
Warning: Interpolation-only expressions are deprecated

  on modules/loader/main.tf line 5, in module "loader_task":
   5:   image   = "${var.loader_image}"
```

2021-12-19 18:57 UTC, Mr0grog commented
Oh, do we also need to stop pushing a `latest` tag here? https://github.com/usdigitalresponse/univaf/blob/71bf9a488a00d5f80e4b2737d61a2901bd9ebd4e/.github/workflows/ci.yml#L194-L202

2021-12-21 00:43 UTC, Mr0grog approved these changes
👍 👍 👍 Merge at will :shipit: :shipit: :shipit:

2021-12-21 02:15 UTC, merged