Allow tests to have transactions
usdigitalresponse/univaf pull request #861
Opened 2022-08-27 18:44 UTC by Mr0grog

Instead of wrapping tests in transactions (and making transactions *inside* the test do nothing), truncate the relevant tables and sequences before each test (not after, so if something goes wrong, that leaves stuff in the DB so you can inspect it).

This also fixes a long-standing issue where Jest would try and run tests in the `dist` directory, which would sometimes lead to incorrect failures (if you hadn’t run a build since changing a test file, the test in `dist` would have the old code and fail).

Fixes #463.

2022-08-27 18:48 UTC, Mr0grog commented
I looked at a couple third-party packages for this ([knex-db-manager](https://www.npmjs.com/package/knex-db-manager) and [knex-tablecleaner](https://www.npmjs.com/package/knex-tablecleaner)), but they were both pretty old (had peer dependencies on Knex < 1.0, and Knex is now at 2.x) had problems with the `CASCADE` issue described in a comment in this code, and one dropped tables instead of truncating them, which is a lot more complicated because it requires us to have a schema to recreate the table. 🤷

2022-08-27 19:02 UTC, astonm requested changes
Cool, this is in accordance with what we wanted from the start, right? Glad you found a way to get the right behavior for clearing out and resetting tables.

One ask: can we find a way to make sure we're only ever running this truncation code on the test database?

2022-08-27 22:09 UTC, Mr0grog commented
> can we find a way to make sure we're only ever running this truncation code on the test database?

Do you have any deeper thoughts about this? It only runs as part of the tests, and only when a test opts into it (same as with the transactions before). We could gate this on the value of `NODE_ENV` (so it only runs with the configuration that gets you the test DB), but then we'd be in a situation where all the tests could run without the DB cleanup, and if they wind up running against a non-test DB, they are still going to make quite a mess.

2022-08-28 00:29 UTC, astonm commented
I think checking `NODE_ENV` would satisfy my worries here. If we asserted the right environment when `installTestDatabaseHooks()` is called, wouldn't that stop tests from running altogether (thus nothing to clean up)?

2022-08-28 15:58 UTC, Mr0grog commented
Ah, that makes more sense. For some reason I was stuck on the idea that you specifically meant `resetDatabase()` not all the database tooling for tests together.

2022-08-28 16:16 UTC, Mr0grog commented
@astonm Ha, I totally forgot we already do that as part of global setup, where we clear the whole database and recreate it from scratch! https://github.com/usdigitalresponse/univaf/blob/62e113fadc55686cc9985747ad498b9fc5386f9b/server/test/globalSetup.ts#L6-L23

So I think there’s nothing that actually needs to change?

2022-08-28 17:31 UTC, astonm approved these changes
Hah, I forgot about that myself... Belt and suspenders would be to add a call to `assertIsTestDatabase()` inside of `installTestDatabaseHooks` on some off chance that code gets called without running through the Jest `globalSetup`, but yeah, I think no need. Good to go here!

2022-08-28 17:48 UTC, Mr0grog commented
👍 I think I'll merge this tomorrow and see about following it up with a quick PR to refactor the modules with test support code so they can share code and move them into a subfolder (mirroring the organization of `loader/test/support`).

2022-08-29 16:46 UTC, merged